x-logging: &logging
  driver: "json-file"
  options:
    max-size: "16m"
    max-file: "16"

services:
  crushmydeck:
    image: ghcr.io/${IMAGE_NAME}:latest
    pull_policy: always

    logging: *logging
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.${ALIAS}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${ALIAS}.entrypoints=https
      - traefik.http.routers.${ALIAS}.tls.certresolver=letsencrypt
      - traefik.http.services.${ALIAS}.loadbalancer.server.port=${APP_PORT}

    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
